front-end: use 'bin' path for node commands instead of '.bin'
license-checker is using relative paths for importing other modules - that
worked fine when .bin/license-checker was a symlink, but not on filesystems
without symlinks support:

  internal/modules/cjs/loader.js:883
    throw err;
    ^

  Error: Cannot find module '../lib/index'