py3: update ssh for base64.b64decode raising binascii.Error instead of TypeError
A command like:
  python -c 'import base64; base64.b64decode("QQ")'
would fail in Python2 with:
  TypeError: Incorrect padding
but in python3:
  binascii.Error: Incorrect padding