setup: bump beaker minimum version to 1.10.1 to get py3 support
1.10.0 failed on py3 because it was using the reserved async keyword:

  File ".../build/minimum-dependency-versions-venv/lib/python3.7/site-packages/beaker/synchronization.py", line 289
    self.async = 0
             ^
SyntaxError: invalid syntax