api: fix 'kallithea-api --save-config'
Commit eca0cb56a822 attempted to fix a type inconsistency, which caused
failure in the 'kallithea-api' tool when using '--save-config', but this
unfortunately did not fix the problem completely.

Following error still appeared:

    Traceback (most recent call last):
      File ".../bin/kallithea-api", line 33, in <module>
        sys.exit(load_entry_point('Kallithea', 'console_scripts', 'kallithea-api')())
      File ".../bin/kallithea_api.py", line 84, in main
        'apihost': args.apihost})
      File ".../bin/base.py", line 104, in __init__
        self.make_config(config)
      File ".../bin/base.py", line 132, in make_config
        ext_json.dump(config, f, indent=4)
      File "/usr/lib/python3.7/json/__init__.py", line 180, in dump
        fp.write(chunk)
    TypeError: a bytes-like object is required, not 'str'

The json module documentation says:
https://docs.python.org/3.7/library/json.html#basic-usage
"The json module always produces str objects, not bytes objects. Therefore,
fp.write() must support str input."

Therefore, instead of opening the file in binary mode and writing bytes,
open it in text mode and write strings.

For symmetry reasons, we make the same change when _loading_ the config
file, but this code worked regardless.