error: remove unused Pylons-specific img/style methods
The img and style methods in the error controller are standard Pylons
boilerplate. They are used from the Pylons default error document template.
The purpose of these methods is to serve images and stylesheets from the
Pylons module, rather than having to copy these files into a particular
application installation.

Since Kallithea uses a custom error template with our own styles and images,
these methods are not actually used.